version: "3.5"
services:
  bind:
    build: ./bind
    container_name: resolver
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 953:953/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bind/dconf:/etc/bind
    entrypoint: ["named", "-g", 
                 "-c", "/etc/bind/named.conf", 
                 "-u", "named"]